# Color themes
LIGHT_MODE = 'Light'
DARK_MODE = 'Dark'

# Colors
SIDEBAR_DARK_BG_COLOR = '#2b2b2b'
SIDEBAR_LIGHT_BG_COLOR = '#dbdbdb'
RESULT_FRAME_LIGHT_BG_COLOR = '#cfcfcf'
RESULT_FRAME_DARK_BG_COLOR = '#333333'
BTN_TEXT_DARK_COLOR = '#DCE4EE'
BTN_TEXT_LIGHT_COLOR = '#333333'
MULTIPLE_RESULT_MAIN_IMG_DIMS = (400, 500)